version: 2

defaults: &defaults
  docker:
    - image: codestar/circleci-scala-sbt-git:scala-2.12.6-sbt-1.1.6

jobs:
  build_project1:
    <<: *defaults
    steps:
      - checkout
      - run: cd project1
      - run: sbt compile

  test_project1:
    <<: *defaults
    steps:
      - checkout
      - run: cd project1
      - run: sbt test:compile test:test

workflows:
  version: 2
  build_and_test_project1:
    jobs:
      - build_project1
      - test_project1:
          requires:
            - build_project1