version: 2

defaults: &defaults
  docker:
    - image: codestar/circleci-scala-sbt-git:scala-2.12.6-sbt-1.1.6
  environment:
    BASH_ENV: ".circleci/bash_env.sh"

jobs:
  compile_shared:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - shared-{{ checksum "shared/build.sbt" }}
      - run:
          name: "Compile shared"
          command: sbt-on-diff shared compile
      - save_cache:
          when: on_success
          key: shared-{{ checksum "shared/build.sbt" }}
          paths:
            - ./target/resolution-cache
            - ./target/streams
            - ./project/target/resolution-cache
            - ./project/target/streams
            - /root/.sbt
            - /root/.ivy2/cache
            - /root/.coursier-cache
            - /root/.m2
      - persist_to_workspace:
          root: shared
          paths:
            - target

  test_shared:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - shared-{{ checksum "shared/build.sbt" }}
      - attach_workspace:
          at: shared
      - run:
          name: "Test shared"
          command: sbt-on-diff shared test:compile test:test


  compile_project1:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - project1-{{ checksum "project1/build.sbt" }}
      - run:
          name: "Compile project1"
          command: sbt-on-diff (project1|shared) compile
      - save_cache:
          when: on_success
          key: project1-{{ checksum "project1/build.sbt" }}
          paths:
            - ./target/resolution-cache
            - ./target/streams
            - ./project/target/resolution-cache
            - ./project/target/streams
            - /root/.sbt
            - /root/.ivy2/cache
            - /root/.coursier-cache
            - /root/.m2
      - persist_to_workspace:
          root: project1
          paths:
            - target

  test_project1:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - project1-{{ checksum "project1/build.sbt" }}
      - attach_workspace:
          at: project1
      - run:
          name: "Test project1"
          command: sbt-on-diff (project1) test:compile test:test


  compile_project2:
      <<: *defaults
      steps:
        - checkout
        - restore_cache:
            keys:
              - project2-{{ checksum "project2/build.sbt" }}
        - run:
            name: "Compile project2"
            command: sbt-on-diff project2 compile
        - save_cache:
            when: on_success
            key: project2-{{ checksum "project2/build.sbt" }}
            paths:
              - ./target/resolution-cache
              - ./target/streams
              - ./project/target/resolution-cache
              - ./project/target/streams
              - /root/.sbt
              - /root/.ivy2/cache
              - /root/.coursier-cache
              - /root/.m2
        - persist_to_workspace:
            root: project2
            paths:
              - target

  test_project2:
      <<: *defaults
      steps:
        - checkout
        - restore_cache:
            keys:
              - project2-{{ checksum "project2/build.sbt" }}
        - attach_workspace:
            at: project2
        - run:
            name: "Test project2"
            command: sbt-on-diff project2 test:compile test:test

workflows:
  version: 2
  build_and_test:
    jobs:
      - compile_shared
      - test_shared:
          requires:
            - compile_shared

      - compile_project1:
          requires:
            - test_shared
      - test_project1:
          requires:
            - compile_project1

      - compile_project2:
          requires:
            - test_shared
      - test_project2:
          requires:
            - compile_project2