version: 2

defaults: &defaults
  docker:
    - image: codestar/circleci-scala-sbt-git:scala-2.12.6-sbt-1.1.6
  environment:
    BASH_ENV: ".circleci/bash_env.sh"

jobs:
  compile_project1:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - project1-{{ checksum "project1/build.sbt" }}
      - run:
          command: |
            pushd project1
            mkdir target
            sbt-on-diff project1 compile
            popd
      - save_cache:
          when: on_success
          key: project1-{{ checksum "project1/build.sbt" }}
          paths:
            - ./target/resolution-cache
            - ./target/streams
            - ./project/target/resolution-cache
            - ./project/target/streams
            - /root/.sbt
            - /root/.ivy2/cache
            - /root/.coursier-cache
            - /root/.m2
      - persist_to_workspace:
          root: project1
          paths:
            - target

  test_project1:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - project1-{{ checksum "project1/build.sbt" }}
      - attach_workspace:
          at: project1
      - run:
          command: |
            pushd project1
            .circleci/bin/execute-on-diff project1 sbt test:compile test:test
            popd


  compile_project2:
      <<: *defaults
      steps:
        - checkout
        - run:
            command: |
              echo "$PATH"
              execute-on-diff project2
        - run: echo compile

  test_project2:
    <<: *defaults
    steps:
      - checkout
      - run: cd project2
      - run: sbt test:compile test:test

workflows:
  version: 2
  build_and_test_project1:
    jobs:
      - compile_project1
      - test_project1:
          requires:
            - compile_project1

      - compile_project2
      - test_project2:
          requires:
            - compile_project2